version: '3'

services:
    database:
      container_name: postgres
      #image: postgres
      image: makomweb/images:postgres-13.1-with-make-4.2.1
      env_file:
        - ./.env
      ports:
        - "5432:5432"
      volumes:
        - .:/home/curious
        - ./postgres-data:/var/lib/postgresql/data

    pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      env_file:
        - ./.env
      ports:
        - "5050:5050"