version: "3.3"

services:
  db:
    container_name: curious_db
    image: curious_db
    build:
      context: ./db
    env_file:
      - ./.env
    ports:
      - 5432:5432
    volumes:
      - .:/home/curious
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    container_name: curious_db_pgadmin
    image: curious_db_pgadmin
    build:
      context: ./pgadmin
    env_file:
      - ./.env
    depends_on:
      - db 
    ports:
      - 5050:5050